import {
  LzButton,
  LzIcon,
  LzButtonGroup,
  LzCollapse,
  LzCollapseItem,
  LzAlert,
  LzTooltip,
  LzPopconfirm,
  LzDropdown,
  LzDropdownItem,
  LzMessage,
  LzNotification,
  LzInput,
  LzMessageBox,
  LzLoading,
} from "@lz-element/components";
import type { Plugin } from "vue";

export default [
  LzButton,
  LzIcon,
  LzButtonGroup,
  LzCollapse,
  LzCollapseItem,
  LzAlert,
  LzTooltip,
  LzPopconfirm,
  LzDropdown,
  LzDropdownItem,
  LzMessage,
  LzNotification,
  LzInput,
  LzMessageBox,
  LzLoading,
] as Plugin[];
